name: Build Android APK

on:
  push:
    branches: '*'
    paths-ignore:
    - README.md
    - LICENSE
    - CONTRIBUTING.md
    - .gitignore
    - '.github/**'
    - '!.github/workflows/android.yml'
    - 'ClientCli/**'
    - 'ServerCli/**'
    - 'ServerShared/**'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-android-build
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        lfs: true

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: platforms/android

    # - name: Prepare gradle.properties for signing
    #   run: |
    #     echo -n '${{ secrets.TEST_APK_SIGNING_STORE_FILE }}' | base64 --decode > ~/app_signing_file.jks
    #     mkdir -p ~/.gradle
    #     echo RELEASE_STORE_FILE=~/app_signing_file.jks >> ~/.gradle/gradle.properties
    #     echo RELEASE_STORE_PASSWORD=${{ secrets.TEST_APK_SIGNING_STORE_PASSWORD }} >> ~/.gradle/gradle.properties
    #     echo RELEASE_KEY_ALIAS=${{ secrets.TEST_APK_SIGNING_KEY_ALIAS }} >> ~/.gradle/gradle.properties
    #     echo RELEASE_KEY_PASSWORD=${{ secrets.TEST_APK_SIGNING_KEY_PASSWORD }} >> ~/.gradle/gradle.properties

    - uses: burrunan/gradle-cache-action@v3
      name: Build with Gradle
      with:
        arguments: build
        build-root-directory: platforms/android

    # - name: Sign the Apk
    #   run: ./gradlew assembleRelease
    #   working-directory: platforms/android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: easy-photo-backup_android-client.apk
        path: |
          platforms/android/app/build/outputs/apk/release/app-release.apk

    - name: Verify Kotlin formatting
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew ktfmtCheck
      working-directory: platforms/android
